version: '3'

networks:
  app-tier:
    driver: bridge

services:
  todo-api:
    build: .
    networks:
      - app-tier
    ports:
      - "3000:3000"
    depends_on:
      - dbsql
    volumes:
      - ".:/todoapidocker/src/app/"
  dbsql:
    image: postgres:12
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASS
      - POSTGRES_DB
    networks:
      - app-tier